from enum import Enum

class METRICNAMES(Enum):
    FLUENCY= 'FLUENCY'
    GRAMMATICAL_CORRECTNESS= 'GRAMMATICAL_CORRECTNESS'
    TONALITY= 'TONALITY'
    FACTUAL_CONSISTENCY= 'FACTUAL_CONSISTENCY'
    CONCEPTUAL_SIMILARITY= 'CONCEPTUAL_SIMILARITY'
    COHERENCE= 'COHERENCE'
    READABILITY= 'READABILITY'
    CLARITY= 'CLARITY'
    DIVERSITY= 'DIVERSITY'
    CREATIVITY= 'CREATIVITY'
    PROMPT_INJECTION= 'PROMPT_INJECTION'
    TOXICITY= 'TOXICITY'
    BIAS= 'BIAS'
    COMPRESSION_SCORE= 'COMPRESSION_SCORE'

    