models:
 - type: main
   engine: openai
   model: gpt-3.5-turbo

rails:
  input:
    flows:
      - check toxicity
  output:
    flows:
      - check toxicity
core:
  embedding_search_provider:
    name: default
    parameters:
      embedding_engine: openai
      embedding_model: text-embedding-ada-002
    cache:
      enabled: False
      key_generator: md5
      store: filesystem
      store_config: {}

knowledge_base:
  embedding_search_provider:
    name: default
    parameters:
      embedding_engine: openai
      embedding_model: text-embedding-ada-002
    cache:
      enabled: False
      key_generator: md5
      store: filesystem
      store_config: {}