prompts:
  - task: self_check_input
    content: |

      User message: "{{ user_input }}"

      Question: Give an answer for the message
      Answer:
  - task: self_check_output
    content: |

      Bot message: "{{ bot_response }}"

      Question: Give an answer for the message
      Answer: